### ISSUE TITLE
Can't run Check-MK

### ISSUE THREAD

**Issue by mslee89** [dkrizic/charts#3]
Hello.
I tried to run Check-MK in Kubernetes.

But, the pod can't work with the log below.

```
### CREATING SITE 'cmk'
Site 'cmk' already existing.
```

How can i fix this?

**Comment by mslee89** [comment]
The cause was found.
Problems occur because temp volumes were already mounted on /omd/sites/cmk/tmp before omd creation.

```
$ cd /omd/sites
$ tree cmk
cmk
`-- tmp

1 directory, 0 files

$ omd create cmk
Site 'cmk' already existing.
```

This does not occur if i delete temp mount settings to resolve this issue.
```
deployment.yaml
          volumeMounts:
            - name: checkmk-sites
              mountPath: /omd/sites
            - name: checkmk-backup
              mountPath: /backup
#            - name: temp
#             mountPath: /omd/sites/cmk/tmp
...
      volumes:
        - name: checkmk-sites
          persistentVolumeClaim:
            claimName: {{ include "checkmk.fullname" . }}-sites
        - name: checkmk-backup
          persistentVolumeClaim:
            claimName: {{ include "checkmk.fullname" . }}-backup
#        - name: temp
#          emptyDir:
#           medium: Memory
```

But I don't think this is a good way. Do you have any other advice?

**Comment by dkrizic** [comment]
I am installing the chart using this command

```
helm repo add groundhog2k https://groundhog2k.github.io/helm-charts/
helm repo add dkrizic https://dkrizic.github.io/charts
helm repo update
kubectl create namespace observium
helm -n observium upgrade --install observium-mariadb -f mariadb.yaml groundhog2k/mariadb
helm -n observium upgrade --install observium -f observium.yaml dkrizic/observium
```

The observierium.yaml looks like this:

```
nodeSelector:
  kubernetes.io/arch: arm64
ingress:
  enabled: true
  hosts:
    - host: observium.krizic.net
      paths: 
      - path: "/"
observium:
  base_url: https://observium.mydomain.com
  server_name: observium.mydomain.com
  tz: "Europe/Berlin"
  admin:
    user: admin
    password: mypassword
  db:
    host: observium-mariadb
    user: observium
    password: mypassword
    name: observium

persistence:
  rrd:
    size: 20Gi
    storageClassName: rook-ceph-block-csi
  logs:
    size: 20Gi
    storageClassName: rook-ceph-block-csi
resources:
  requests:
    cpu: 1500m
  limits:
    cpu: 2800m
```

It is essential to have the volumes specified. The intention is, that you don't have to change the Helm chart at all.

**Comment by dkrizic** [comment]
Just to clarify, the used Docker image creates the site "omd" by itself. After installing the chart there is no need to do anything manually. After a while (take a look in the log) the site "omd" should be there and you can login with the provided password.

**Comment by dkrizic** [comment]
Sorry, my comment from before was about a wrong helm chart. I am installing CheckMK like this:

```
kubectl create namespace checkmk
helm -n checkmk upgrade --install checkmk -f checkmk.yaml dkrizic/checkmk
```

and I am using the configuration file checkmk.yaml

```
image:
  repository: joeri2821/check-mk-raw-pi
  tag: 2.0.0P3-arm64
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  hosts:
  - host: <my-host-name>
    paths: 
    - path: "/"
nodeSelector:
  kubernetes.io/arch: arm64
persistence:
  size: 50Gi
  storageClassName: ""
backup:
  size: 50Gi
  storageClassName: ""
resources:
  requests:
    cpu: 2500m
  limits:
    cpu: 3800m
```

The site "omd" is created automatically, there is no need for doing any manual steps. I think this is the reason why it did not work for you, you tried to create "omd" by yourself, but it was done by Container itself.
